### PR TITLE
Make collections imports work in Python 3.10

### PR DESCRIPTION
**Pull request by sea-bass**
In Python 3.10, a couple of things were moved out of the `collections` module and into `collections.abc`. See, for example https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python

These slight tweaks make it so that the focused and incremental algorithms work in Python 3.10 without breaking older versions.

### CODE REVIEW

**Comment by sea-bass** [comment]
An alternative is to do this switch based on another version of Python. Officially, the `collections.abc` module was introduced in Python 3.3 ([reference](https://docs.python.org/3/library/collections.abc.html)), but there just still happened to be aliases that kept this compatible up until Python 3.9.

So options would be:

1. Do the switch around Python 3.10 (as this PR does now)
2. Do the switch around Python 3.3 (the true version `collections.abc` became a thing)
3. Do the switch around Python 2 vs. Python 3 (assuming nobody is using Python 3 below version 3.3)

**Comment by sea-bass** [comment]
An alternative is to do this switch based on another version of Python. Officially, the `collections.abc` module was introduced in Python 3.3 ([reference](https://docs.python.org/3/library/collections.abc.html)), but there just still happened to be aliases that kept this compatible up until Python 3.9.

So options would be:

1. Do the switch around Python 3.10 (as this PR does now)
2. Do the switch around Python 3.3 (the true version `collections.abc` became a thing)
3. Do the switch around Python 2 vs. Python 3 (assuming nobody is using Python 3 below version 3.3)

**Comment by AzureViolin** [comment]
Hi @sea-bass 

I was facing the same issue and did the same thing, but didn't get around to doing a pull request yet. Glad you did this, thanks! I've tested your commit and it worked on Ubuntu 22.04, 7 out of 10 examples work out of the box after your commit. The remaining three are PR2 TAMP, PR2 Cleaning and Cooking, and Turtlebot Rovers.

I've fixed the PR2 TAMP example by updating how `MutableSet` is imported in `pddlstream/examples/pybullet/utils/pybullet_tools/utils.py`, however, there are two examples I'm not sure how to fix.

in PR2 Cleaning and Cooking example, the error is:
`"pddlstream/examples/pybullet/pr2/run.py", line 84, in opt_move_cost_fn
    q1, q2 = t.values
AttributeError: 'UniqueOptValue' object has no attribute 'values'`

while in Turtlebot Rovers example, the error is:
`pddlstream/examples/pybullet/utils/pybullet_tools/utils.py", line 3476, in collision_fn
    if (not use_aabb or aabb_overlap(get_moving_aabb(body1), get_obstacle_aabb(body2))) \
TypeError: 'property' object is not callable`

I plan to fix these and then do a pull request so it is convenient for later users. Wonder if you have already solved these and can show me some pointers. Thanks!

**Comment by sea-bass** [comment]
Ah, good find! I actually did not even try out the canned examples with the repo -- I just fixed the import issues as I am in the process of creating my own examples.

So if you stack your fixes on top of these, that would be fantastic!

**Comment by sea-bass** [comment]
I was able to get the PR2 TAMP and TurtleBot Rovers examples working in 3.10, but the PyBullet `utils` and `motion` are submodules so those have to be updated too.

File: examples/pybullet/turtlebot_rovers/streams.py [hunk 1]
```diff
@@ -46,7 +46,7 @@ def get_reachable_test(problem, iterations=10, **kwargs):
     initial_confs = {rover: Conf(rover, get_base_joints(rover))
                      for rover in problem.rovers}
     # TODO: restarts -> max_restarts
-    motion_fn = get_motion_fn(problem, restarts=0, max_iterations=iterations, smooth=0, **kwargs)
+    motion_fn = get_motion_fn(problem, restarts=0, iterations=iterations, smooth=0, **kwargs)
```
Comment (sea-bass) [inline examples/pybullet/turtlebot_rovers/streams.py:49]: In the latest commit of the `motion` submodule, this argument name was changed to `max_iterations` ... so I'm not sure what we want to do here, actually. Just pull in a newer SHA of the `motion` submodule?

Comment (AzureViolin) [reply examples/pybullet/turtlebot_rovers/streams.py:49]: Hmm did you change anything else other than the variable name `max_iterations` to `iternations` to make the turtlebot rover example work? I did the same and still got the same error I reported in the previous comment.

File: pddlstream/algorithms/instantiation.py [hunk 2]
```diff
@@ -1,4 +1,9 @@
-from collections import defaultdict, namedtuple, Sized
+import sys
+from collections import defaultdict, namedtuple
+if sys.version_info >= (3, 10):
```
Comment (AzureViolin) [inline pddlstream/algorithms/instantiation.py:3]: Is there a reason to prefer using `sys.version_info` over `try`?
```
try:
    from collections.abc import Sized
except ImportError:
    from collections import Sized
```

**Comment by AzureViolin** [comment]
> I was able to get the PR2 TAMP and TurtleBot Rovers examples working in 3.10, but the PyBullet `utils` and `motion` are submodules so those have to be updated too.

Where exactly in `motion` needs to be updated to make TurleBot Rovers work?

> 
> I've never really worked with Git submodules so curious how this all works. Do I need to make my own forks of the submodules and put up separate PRs to each of those? And then have this PR update the commit hash of those submodules? And how do we deal with the fact that the current commits of the submodules aren't necessarily the latest?

Me neither. I believe what you've stated here is the way to go and I did a PR for fixing PR2 TAMP example on top of your first commit `f067901bfabd3cd1a21ae42ef2088733eb1da476`: https://github.com/caelan/pybullet-planning/pull/11
According to https://git-scm.com/book/en/v2/Git-Tools-Submodules, the super project (`pddlstream` in this case) needs to specify the correct commit of the submodules for users to get the correct commit through `pddlstream$ git pull --recurse-submodules`
> 
> No clue on the PR2 Cleaning / Cooking example. It seems that some of the functions in place do not like that there are `UniqueOptValue` instances where not expected.

Thanks for looking into it. We'll let someone else figure it out then. There are enough examples already, after all.

File: examples/pybullet/turtlebot_rovers/streams.py (hunk 1 above)
Comment (sea-bass) [reply examples/pybullet/turtlebot_rovers/streams.py:49]: Yes! In the `pybullet-utils` repo, namely `utils.py` I also had to make this change in the definition of the `wrapped` function:

```
    #from functools import lru_cache as cache
    # @cache(maxsize=None, typed=False)
    if sys.version_info >= (3, 9):
        from functools import cache # New in version 3.9
        @cache
        def wrapped(*args, **local_kwargs):
            return normal(*args, **local_kwargs)
        return wrapped
    else:
        // This was the old function
        @cache_decorator
        def wrapped(*args, **local_kwargs):
            return normal(*args, **local_kwargs)
        return wrapped 
```

**Comment by caelan** [comment]
Closing in favor of: https://github.com/caelan/pddlstream/commit/f503b7f10ccf88dfc892fd14481d74059e97874a
